name: Run To Test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn run test
