name: Run To Test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install yarn
      run: npm i -g yarn

    - name: Install Dependency
      run: yarn install

    - name: Test
      run: yarn run test
